### ISSUE TITLE
Increase the Storke Width

### ISSUE THREAD

**Issue by rk8339811** [castorflex/SmoothProgressBar#107] opened 2018-07-24 14:19 UTC
I am planning to use this lovely library in my Android App.

But the issue I am facing is that Stroke size is not increasing even after setting it to increase. The size of the Stroke is same even If I set to 50dp or 150dp.

Is there any way to increase it ?

**Comment by castorflex** [comment] 2021-05-21 17:18
Closing because the issue is too old. Please reopen it if you're facing the same issue

**Closed by castorflex** 2021-05-21 17:18 UTC
