### ISSUE TITLE
Same code different progress bars

### ISSUE THREAD

**Issue by srujanb** [castorflex/SmoothProgressBar#93] opened 2017-02-02 14:20 UTC
I am using the same code at two places and both showing different progress bars. 

Code:
    <fr.castorflex.android.smoothprogressbar.SmoothProgressBar
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:indeterminate="true"
        app:spb_sections_count="4"
        app:spb_color="#FF0000"
        app:spb_speed="1.0"
        app:spb_stroke_width="4dp"
        app:spb_stroke_separator_length="4dp"
        app:spb_reversed="false"
        app:spb_mirror_mode="false"
        app:spb_progressiveStart_activated="true"
        app:spb_progressiveStart_speed="1.5"
        app:spb_progressiveStop_speed="3.4"
        />

The progress bar in the dialogsheet shows blue and the one in the activity shows red.

![pb_bug](https://cloud.githubusercontent.com/assets/5074876/22552906/ca6383f6-e980-11e6-984f-95e02a9d7401.png)

**Comment by castorflex** [comment] 2017-08-27 14:39
Hello, would you have a sample project to reproduce it on my end? thanks

**Comment by castorflex** [comment] 2021-05-21 17:20
Closing because the issue is too old. Please reopen it if you're facing the same issue

**Closed by castorflex** 2021-05-21 17:20 UTC
