### ISSUE TITLE
App crashes 

### ISSUE THREAD

**Issue by GalaxyS5S6S7S8** [castorflex/SmoothProgressBar#94] opened 2017-03-18 18:16 UTC
Wehen i use it directly in xml my app crashes! Tutorial (auf deutsch: Kompliziert! und nicht verständlich!) Please help me

**Comment by daimonkor** [comment] 2017-03-23 18:37
Please help, xml inflate error.  
multiDexEnabled true
 compileSdkVersion 25
 buildToolsVersion "25.0.2"
![alt error](http://image.prntscr.com/image/3b18aa44570e499ea01d7ed5c6e1153f.png)
![alt layout](http://image.prntscr.com/image/0d0c5a477aed402b9bfb544c7f0ebbae.png)

**Comment by guness** [comment] 2017-04-29 00:05
sometimes getting same. it is also happend on Production. shame on me 👎

**Comment by castorflex** [comment] 2021-05-21 17:20
Closing because the issue is too old. Please reopen it if you're facing the same issue

**Closed by castorflex** 2021-05-21 17:20 UTC
