### ISSUE TITLE
Not working after upgrading to api level 26 with android studio 3.0: Error inflating class fr.castorflex.android.circularprogressbar.CircularProgressBar

### ISSUE THREAD

**Issue by nizamsp** [castorflex/SmoothProgressBar#98] opened 2017-08-12 19:27 UTC
>  Process: com.whereismytrain.android.debug, PID: 29061
>                                                                                   android.view.InflateException: Binary XML file line #22: Binary XML file line #22: Error inflating class fr.castorflex.android.circularprogressbar.CircularProgressBar
>                                                                                   Caused by: android.view.InflateException: Binary XML file line #22: Error inflating class fr.castorflex.android.circularprogressbar.CircularProgressBar
>                                                                                   Caused by: java.lang.reflect.InvocationTargetException
>                                                                                       at java.lang.reflect.Constructor.newInstance0(Native Method)
>                                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
>                                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:645)
>                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:787)
>                                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
>                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:858)
>                                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
>                                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:861)
>                                                                                       at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:821)
>                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:518)
>                                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:426)
>                                                                                       at com.whereismytrain.activities.PnrMasterFragment.onCreateView(PnrMasterFragment.java:144)
>                                                                                       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2343)
>                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1419)
>                                                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
>                                                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
>                                                                                       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
>                                                                                       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
>                                                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
>                                                                                       at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
>                                                                                       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
>                                                                                       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
>                                                                                       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:167)
>                                                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
>                                                                                       at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
>                                                                                       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1060)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                                       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                                                       at android.view.View.measure(View.java:19857)
> 08-13 00:55:35.988 29061-29061/com.whereismytrain.android.debug E/AndroidRuntime:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
>                                                                                       at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
>                                                                                       at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6083)
>                                                                                       at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
>                                                                                       at com.android.internal.policy.DecorView.onMeasure(DecorView.java:689)
>                                                                                       at android.view.View.measure(View.java:19857)
>                                                                                       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2275)
>                                                                                       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1366)
>                                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1619)
>                                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
>                                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
>                                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
>                                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:686)
>                                                                                       at android.view.Choreographer.doFrame(Choreographer.java:621)
>                                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
>                                                                                       at android.os.Handler.handleCallback(Handler.java:751)
>                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                                       at android.os.Looper.loop(Looper.java:154)
>                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6119)
>                                                                                       at java.lang.reflect.Method.invoke(Native Method)
>                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
>                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
>                                                                                    Caused by: java.lang.UnsupportedOperationException: Can't convert value at index 3 to dimension: type=0x10
>                                                                                       at android.content.res.TypedArray.getDimension(TypedArray.java:621)
>                                                                                       at fr.castorflex.android.circularprogressbar.CircularProgressBar.<init>(CircularProgressBar.java:36)
>                                                                                       at fr.castorflex.android.circularprogressbar.CircularProgressBar.<init>(CircularProgressBar.java:20)

**Comment by pepitoria** [comment] 2017-08-21 10:14
this is happening to me too. on the normal library, not the circular though.

**Comment by JuniusAng** [comment] 2017-08-24 14:57
I think the issue caused aapt2 being enabled by default in AS gradle plugins 3.0.
For temporary fix try to add this into your gradle.properties

android.enableAapt2=false

and please confirm if this also fix your project.

**Comment by nizamsp** [comment] 2017-08-24 15:20
Yes. The fix worked. But will this affect my other projects?

**Comment by JuniusAng** [comment] 2017-08-24 17:47
I think no. The issue possibly lies on aapt2. But we will try to test it more later.

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by castorflex** [comment] 2017-08-27 14:34
I guess this issue is related to this one https://stackoverflow.com/questions/44196672/aapt2-compile-failed-invalid-dimen-on-android-3-0-canary-1

Could you try setting LC_NUMERIC? I don't have the error on my end

**Comment by youtoou2** [comment] 2017-08-28 10:55
same issue and temp fixed with android.enableAapt2=false

**Comment by imorlowska** [comment] 2017-09-15 16:45
I debugged this issue for one of your users and it looks like they had a dependency on a version/fork of your library that was built using a very old version of build tools that had a bug which caused the attributes under declare styleables to be compiled as final in the R.java. This in turn resulted in the resource IDs being inlined in the code of the library and since the ordering of resources changed in AAPT2 this results in the reported error. The fact that it worked so far with AAPT1 is only pure luck. For those having this issue updating the version of this library to the newest one ('com.github.castorflex.smoothprogressbar:library:1.1.0') fixes this issue, no need to disable AAPT2.

**Comment by vad-zuev** [comment] 2017-09-18 08:08
@imorlowska `implementation 'com.github.castorflex.smoothprogressbar:library-circular:1.0.1'` AFAIK this is the latest version for the round one. Crashes with the error given by the OP on API 24, AS 3.0, Gradle 3.0.0. The only solution that currently works for me is to disable aapt 2

**Comment by mnchiu** [comment] 2017-11-07 06:55
Is there any update on this issue?

**Comment by jzurek** [comment] 2017-12-19 13:41
Is there any other temporary solution than disabling aapt2? When I add
`android.enableAapt2=false` to my `gradle.properties`, I get many other errors.

**Comment by castorflex** [comment] 2021-05-21 17:20
Closing because the issue is too old. Please reopen it if you're facing the same issue

**Closed by castorflex** 2021-05-21 17:20 UTC
