### ISSUE TITLE
My CircularProgressBar not displaying. Why?

### ISSUE THREAD

**Issue by jacobg** [castorflex/SmoothProgressBar#77] opened 2015-06-02 19:23 UTC
My code is below. Root is a WebView, more specifically CordovaWebView:

``` java
                me.progressBar = new CircularProgressBar(me.activity);
                root.addView(me.progressBar, 200, 200);
                root.bringChildToFront(me.progressBar);

                CircularProgressDrawable.Builder builder = new CircularProgressDrawable
                    .Builder(me.activity)
                    .color(Color.WHITE)
                    .sweepSpeed(1.0f)
                    .rotationSpeed(1.0f)
                    .strokeWidth(2)
                    .minSweepAngle(10)
                    .maxSweepAngle(30)
                ;
                CircularProgressDrawable circularProgressDrawable = builder.build();
                me.progressBar.setIndeterminateDrawable(circularProgressDrawable);
```

To isolate any other issues such as layout, I added the following line of code and a black square appears in the top left as it should:

``` java
                me.progressBar.setBackgroundColor(Color.BLACK);
```

I also tried the stock ProgressBar and it displays fine:

``` java
                me.progressBar = new ProgressBar(me.activity);
                root.addView(me.progressBar, 200, 200);
                root.bringChildToFront(me.progressBar);
```

**Comment by castorflex** [comment] 2021-05-21 17:21
Closing because the issue is too old. Please reopen it if you're facing the same issue

**Closed by castorflex** 2021-05-21 17:21 UTC
